name: Auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "contrib" ]

jobs:

  test:

    runs-on: euleros-2.10.1

    steps:
    - name: download
      run: wget "https://cangjie-lang.cn/v1/files/auth/downLoad?nsId=142267&fileName=Cangjie-0.53.13-linux_x64.tar.gz&objectKey=6719f1eb3af6947e3c6af327" -q -O Cangjie-0.53.13-linux_x64.tar.gz && tar -xzf Cangjie-0.53.13-linux_x64.tar.gz
    - uses: checkout-action@0.0.1
    - name: test
      run: . cangjie/envsetup.sh && cjc --version && cd repo_workspace && cjpm update && cjpm build  && cjpm test --parallel true --no-color