name: CI Main

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: euleros-2.10.1
    steps:
      - name: Checkout 
        uses: checkout-action@0.0.1
        with:
          ref: 'main'

      - name: Download Cangjie
        run: |
          wget "https://cangjie-lang.cn/v1/files/auth/downLoad?nsId=142267&fileName=Cangjie-0.53.13-linux_x64.tar.gz&objectKey=6719f1eb3af6947e3c6af327" -q -O Cangjie-0.53.13-linux_x64.tar.gz 
          tar -xzf Cangjie-0.53.13-linux_x64.tar.gz
      
      - name: Build Unit tests
        run: |
          . cangjie/envsetup.sh
          cd repo_workspace
          cjpm update
          cjpm test --no-run --no-color -j3

      - name: Run Unit tests
        run: |
          . cangjie/envsetup.sh
          cd repo_workspace
          export cjHeapSize=1GB
          cjpm test --skip-build --parallel true --no-color